// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG4VVM71TiPhWZ8-1i-g8b7Sm3SfVyY7c',
    appId: '1:842874380689:android:ef362c24c6a11deb8d3a30',
    messagingSenderId: '842874380689',
    projectId: 'colorfindlddm',
    storageBucket: 'colorfindlddm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1luo2Qs5BYmM6Om81t5SmqvZCmf-1w6g',
    appId: '1:842874380689:ios:cfb469036b65ce948d3a30',
    messagingSenderId: '842874380689',
    projectId: 'colorfindlddm',
    storageBucket: 'colorfindlddm.appspot.com',
    iosClientId: '842874380689-lv5474g58116qd77iaet0o5j5397o5ou.apps.googleusercontent.com',
    iosBundleId: 'br.com.colorfind.colorFind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1luo2Qs5BYmM6Om81t5SmqvZCmf-1w6g',
    appId: '1:842874380689:ios:cfb469036b65ce948d3a30',
    messagingSenderId: '842874380689',
    projectId: 'colorfindlddm',
    storageBucket: 'colorfindlddm.appspot.com',
    iosClientId: '842874380689-lv5474g58116qd77iaet0o5j5397o5ou.apps.googleusercontent.com',
    iosBundleId: 'br.com.colorfind.colorFind',
  );
}
